#!/bin/sh
# chkconfig: 35 99 1
# description: meego-tv-IRinterface daemon

# Script name can be the called name, or something more meaningful.
SCRIPTNAME=$0
PATH=/usr/local/bin:/usr/bin:/bin:/sbin

. /etc/init.d/init_utilities

start_function() {
    try_command ir-interface /usr/share/ir_interface/sample.map &
}

stop_function() {
    try_command killall ir-interface
}

status_function() {
    if ps -ax | grep ir-interface >/dev/null 2>&1 ; then
        echo $"ir-interface daemon is running"
        RETVAL=0
    else
        echo $"no ir-interface daemon"
        RETVAL=3
    fi
}

case $1 in
    "start")
    echo "start to run meego-tv-irInterface daemon"
    start_function
    ;;
    "stop")
    stop_function
    ;;
    "restart")
    stop_function
    start_function
    ;;
    "status")
    status_function
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
esac
